<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Blog;
use App\Models\BlogCategory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Blog>
 */
class BlogFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */

    protected $model = Blog::class;

    public function definition()
    {
        $category = BlogCategory::inRandomOrder()->first();

        $productData = [];

        switch ($category->blog_category_name) {
            case 'pc-games':
                $productData = [
                    'blog_title' => $this->faker->randomElement(['Epic Adventures Await: Latest PC Game Releases', 'Top Picks for PC Gamers: Must-Play Titles', 'Explore the Virtual Worlds: PC Gaming Highlights', 'Unleash Your Inner Gamer: New PC Games', 'Discover the Thrill of PC Gaming: Exciting Releases', 'Dive into Gaming Excellence: PC Game Reviews']),
                    'blog_description' => $this->faker->randomElement(['Discover the latest and greatest PC games that will transport you to new realms.', 'Explore a world of gaming with our curated list of top PC game picks', 'Find out what\'s trending in PC gaming with our comprehensive reviews and insights.', 'Get ready for an adventure with these exciting new PC game releases.', 'Experience the thrill of gaming with these handpicked PC titles.', 'Unlock the secrets of these new PC games and embark on unforgettable journeys.']),
                    'content' => $this->faker->randomElement([
                        'Dive into the vibrant world of PC gaming where each release brings a new wave of excitement and adventure. From sprawling open-world RPGs to heart-pounding first-person shooters, PC games continue to push the boundaries of what\'s possible in virtual entertainment. Imagine exploring distant galaxies, battling mythical creatures, or unraveling intricate mysteries—all from the comfort of your gaming setup. With stunning visuals, immersive soundtracks, and gameplay mechanics that challenge and reward, these titles promise endless hours of joy and discovery. Whether you\'re a seasoned gamer or new to the scene, PC games offer something thrilling for every player.',
                        'Step into the shoes of legendary heroes, cunning strategists, and daring adventurers with the latest PC game releases. Each title invites you to embark on a unique journey filled with memorable characters, gripping narratives, and pulse-pounding action. Whether you\'re forging alliances in a fantasy realm, leading troops into battle on distant planets, or solving complex puzzles to uncover ancient secrets, these games offer an escape into worlds limited only by imagination. Immerse yourself in rich storytelling, explore breathtaking landscapes, and master gameplay mechanics that keep you coming back for more. PC gaming is not just a hobby—it\'s an experience that leaves a lasting impression.',
                        'Experience the thrill of PC gaming with a diverse lineup of titles that cater to every taste and preference. Whether you crave intense competitive matches or prefer to lose yourself in a deep narrative, the world of PC games has something for everyone. Discover hidden treasures in forgotten tombs, challenge your reflexes in high-speed races, or build and manage sprawling civilizations—all within the virtual realms crafted by talented developers. Each game offers a unique blend of creativity, innovation, and technical prowess, ensuring that every session is filled with excitement and satisfaction. Explore new horizons, forge unforgettable memories, and join a global community of gamers who share your passion for digital adventures.',
                        'Dive into the exhilarating world of PC gaming, where every click of the mouse and keystroke brings you deeper into immersive digital landscapes and thrilling adventures. Whether you\'re commanding armies in epic real-time strategy battles, exploring vast open worlds teeming with secrets and challenges, or unraveling intricate mysteries in atmospheric point-and-click adventures, PC games offer limitless possibilities for exploration and excitement. Customize your characters, hone your skills, and embark on quests that test your strategic thinking and reflexes. From fast-paced action games to thought-provoking simulations, the PC gaming experience caters to a diverse audience of players seeking adrenaline-pumping thrills and unforgettable storytelling. Join online communities, compete in multiplayer arenas, and forge alliances with fellow gamers as you carve your path to victory and glory in the ever-evolving world of PC gaming.',
                        'Unleash your inner hero and embark on epic quests in the dynamic world of PC games, where each adventure promises a unique blend of action, strategy, and storytelling. Whether you\'re navigating treacherous dungeons in search of legendary treasures, engaging in intense battles against formidable foes, or building sprawling cities from the ground up, PC games offer a vast playground of possibilities. Immerse yourself in richly detailed environments, interact with complex characters, and make impactful decisions that shape the course of your journey. With a wide range of genres to explore, from fantasy epics to futuristic dystopias, PC games cater to diverse tastes and preferences, ensuring there\'s always something new to discover and enjoy. Challenge your skills, unravel mysteries, and forge alliances as you strive to conquer daunting challenges and emerge victorious in the ever-expanding realm of PC gaming.',
                        'Step into the realm of PC gaming and experience a world where creativity, strategy, and skill converge to create unforgettable adventures and experiences. From commanding starships in deep space to managing thriving civilizations on distant planets, PC games offer a diverse array of genres and themes to suit every player\'s taste. Embark on thrilling quests, solve intricate puzzles, and engage in dynamic battles that test your reflexes and strategic thinking. Whether you prefer single-player epics or multiplayer showdowns, PC gaming provides endless opportunities for exploration and mastery. Immerse yourself in meticulously crafted worlds, interact with compelling characters, and uncover hidden secrets as you embark on journeys that transcend the boundaries of imagination. With cutting-edge graphics, immersive soundscapes, and innovative gameplay mechanics, PC games continue to push the boundaries of interactive entertainment, offering unparalleled depth and excitement for players around the globe.',
                    ]),
                ];
                break;

            case 'pc-components':
                $productData = [
                    'blog_title' => $this->faker->randomElement(['Upgrade Your Rig: Essential PC Components', 'Boost Your Gaming Experience: Top PC Hardware', 'Build Your Dream PC: Latest Components', 'Enhance Your Setup: Must-Have PC Gear', 'Revolutionize Your Gaming: Cutting-Edge PC Parts', 'Power Up Your Rig: Advanced PC Components']),
                    'blog_description' => $this->faker->randomElement(['Explore essential PC components that will take your gaming experience to the next level.', 'Upgrade your gaming rig with top-notch hardware and components.', 'Discover the latest advancements in PC components and gear.', 'Enhance your setup with must-have PC components designed for gamers.', 'Revolutionize your gaming setup with cutting-edge PC parts.', 'Power up your rig with advanced PC components that deliver unparalleled performance.']),
                    'content' => $this->faker->randomElement([
                        'Enhance your gaming setup with the latest PC components designed to elevate performance and maximize efficiency. From state-of-the-art processors and graphics cards to lightning-fast SSDs and advanced cooling solutions, these components form the backbone of a powerful gaming rig. Experience seamless gameplay with reduced loading times, crystal-clear graphics, and responsive controls that enhance your competitive edge. Whether you\'re building a new PC from scratch or upgrading your current setup, our curated selection ensures that you have access to cutting-edge technology that meets the demands of modern gaming. Transform your gaming experience with components that deliver unparalleled speed, reliability, and innovation.',
                        'Unlock the potential of your gaming rig with high-performance PC components that set new standards for speed and efficiency. Dive into immersive worlds with graphics cards that render lifelike visuals and processors that handle complex calculations with ease. Whether you\'re exploring vast open worlds, engaging in fast-paced multiplayer battles, or creating content that pushes the limits of creativity, these components provide the horsepower you need to stay ahead of the competition. Invest in reliability and performance that you can count on, ensuring that every gaming session is smooth, responsive, and visually stunning. Elevate your gaming experience to the next level with components that redefine what\'s possible in PC technology.',
                        'Build your dream gaming setup with top-rated PC components that deliver exceptional performance and reliability. From cutting-edge CPUs and GPUs to high-speed RAM and robust motherboards, these components are designed to meet the demands of today\'s most demanding games and applications. Whether you\'re a competitive gamer seeking the highest frame rates and lowest latency or a content creator looking for seamless multitasking and rendering, our selection of PC components ensures that you have the tools to succeed. Experience faster load times, smoother gameplay, and enhanced graphics quality that transform your gaming experience from ordinary to extraordinary. Upgrade with confidence and unleash the full potential of your gaming rig with components that are built to perform.',
                        'Explore the world of PC components where innovation meets performance, and every upgrade brings you closer to achieving your ultimate computing goals. Whether you\'re building a powerhouse gaming rig capable of running the latest AAA titles at maximum settings or assembling a sleek workstation optimized for creative endeavors, PC components offer unparalleled versatility and customization options. Choose from a wide range of processors, graphics cards, motherboards, and storage solutions to tailor your system to meet your specific needs and preferences. Enhance your gaming experience with lightning-fast SSDs that reduce load times and improve responsiveness, or boost productivity with high-performance CPUs that handle intensive tasks with ease. With cutting-edge technologies and groundbreaking advancements, PC components empower you to unleash the full potential of your digital ambitions and create immersive experiences that defy expectations.',
                        'Transform your PC into a performance powerhouse with a curated selection of components designed to elevate your gaming and computing experience to new heights. Whether you\'re a seasoned enthusiast or a first-time builder, our range of processors, graphics cards, memory modules, and cooling solutions provide the tools you need to customize and optimize your system for peak performance. Dive into the latest gaming adventures with graphics cards that deliver stunning visuals and fluid gameplay, or tackle demanding tasks with processors that offer unrivaled speed and efficiency. With innovative features like RGB lighting, advanced cooling systems, and intuitive overclocking tools, PC components allow you to personalize your setup and showcase your unique style. Join a community of passionate gamers and creators who share your passion for technology and innovation, and discover the limitless possibilities of building your dream PC.',
                        'Elevate your gaming experience and unleash the full potential of your PC with a comprehensive selection of components engineered for performance, reliability, and innovation. Whether you\'re upgrading your existing system or building a new one from scratch, our range of processors, graphics cards, storage solutions, and peripherals offer unmatched versatility and cutting-edge features. Immerse yourself in high-fidelity gaming environments with graphics cards that deliver stunning visuals and smooth frame rates, or enhance productivity with processors that handle multitasking with ease. From RGB-lit motherboards that add a touch of style to advanced cooling solutions that keep temperatures in check, PC components provide the tools you need to create a personalized setup that reflects your gaming style and preferences. Join a community of enthusiasts and professionals who rely on our products to push the boundaries of performance and redefine what\'s possible in PC gaming and computing.',
                    ]),
                ];
                break;

            case 'console-games':
                $productData = [
                    'blog_title' => $this->faker->randomElement(['Explore the World of Console Gaming: Latest Releases', 'Top Picks for Console Gamers: Must-Play Titles', 'Dive into Console Gaming Excellence: New Games', 'Unlock the Thrill of Gaming: Console Highlights', 'Discover the Magic of Console Games: Exciting Releases', 'Embark on a Gaming Journey: Console Game Reviews']),
                    'blog_description' => $this->faker->randomElement(['Discover the latest and greatest console games that will captivate players of all ages.', 'Explore a world of gaming with our curated list of top console game picks.', 'Find out what\'s trending in console gaming with our comprehensive reviews and insights.', 'Get ready for an adventure with these exciting new console game releases.', 'Experience the thrill of gaming with these handpicked console titles.', 'Unlock the secrets of these new console games and embark on unforgettable journeys.']),
                    'content' => $this->faker->randomElement([
                        'Immerse yourself in the thrilling world of console gaming with the latest releases that promise unforgettable adventures and captivating storytelling. From epic action epics to heartwarming indie gems, console games offer a diverse range of experiences that cater to every gamer\'s taste. Embark on heroic quests, engage in intense multiplayer battles, or explore breathtaking landscapes teeming with secrets and mysteries. Each title invites you to step into the shoes of extraordinary characters, face formidable challenges, and make meaningful choices that shape the course of your virtual journey. Whether you prefer the adrenaline rush of high-octane action or the emotional depth of narrative-driven gameplay, console games deliver moments of excitement and immersion that leave a lasting impression.',
                        'Discover a world of limitless possibilities with console games that push the boundaries of creativity and innovation. From blockbuster franchises to groundbreaking indie darlings, each title offers a unique blend of gameplay mechanics, artistic design, and storytelling prowess. Dive into vibrant worlds filled with dynamic characters, intricate lore, and interactive environments that invite exploration and discovery. Whether you\'re embarking on a quest for redemption, unraveling the mysteries of an ancient civilization, or forging alliances in a galaxy far, far away, console games provide experiences that resonate long after the credits roll. Join a community of passionate gamers and embark on epic adventures that redefine what it means to play.',
                        'Experience the magic of console gaming with a curated selection of new releases that capture the essence of adventure, challenge, and excitement. From pulse-pounding action to thought-provoking narratives, these games transport you to fantastical realms and distant galaxies where anything is possible. Engage in thrilling battles, solve intricate puzzles, and forge friendships in worlds brought to life by cutting-edge technology and artistic vision. Whether you\'re a veteran gamer or new to the console scene, our collection of games offers something for everyone. Immerse yourself in stories that inspire, gameplay that captivates, and moments that redefine your expectations of what gaming can be.',
                        'Immerse yourself in the thrilling world of console gaming, where every controller button press and cinematic cutscene transports you to immersive worlds filled with adventure, action, and intrigue. Whether you\'re embarking on epic quests in sprawling open-world adventures, engaging in intense multiplayer battles with friends, or unraveling gripping narratives in story-driven masterpieces, console games offer unparalleled entertainment and excitement. Experience the adrenaline rush of high-speed racing, the strategic depth of tactical warfare, and the thrill of competitive sports simulations as you explore diverse genres and experiences. With iconic franchises and groundbreaking exclusives, console gaming delivers unforgettable moments and endless replayability that captivate players of all ages and skill levels. Join millions of gamers worldwide in celebrating the magic of console gaming and discover why it remains a cornerstone of interactive entertainment for generations.',
                        'Step into the realm of console gaming and embark on unforgettable journeys through captivating worlds and thrilling adventures. Whether you\'re wielding powerful weapons in pulse-pounding shooters, mastering intricate combos in fast-paced fighting games, or exploring mysterious dungeons in role-playing epics, console games offer a diverse array of experiences that cater to every gamer\'s taste. Immerse yourself in cinematic storytelling, breathtaking graphics, and innovative gameplay mechanics that push the boundaries of what\'s possible in interactive entertainment. With exclusive titles, multiplayer experiences, and downloadable content that expands your gaming horizons, consoles provide endless opportunities for discovery and enjoyment. Connect with friends online, compete in global tournaments, and create lasting memories as you explore the rich tapestry of gaming experiences that define the console gaming landscape.',
                        'Discover the magic of console gaming and embark on epic adventures that transport you to new worlds, challenge your skills, and ignite your imagination. Whether you\'re piloting starfighters in deep space, battling mythical creatures in fantasy realms, or leading squads of soldiers in intense military campaigns, console games offer a vast array of genres and experiences to suit every player\'s preferences. Immerse yourself in stunning visuals, immersive soundscapes, and engaging narratives that unfold with each new level and story beat. From blockbuster hits to indie gems, console gaming delivers a curated selection of titles that promise excitement, intrigue, and countless hours of entertainment. Join a global community of gamers who share your passion for exploration, competition, and camaraderie, and experience firsthand why console gaming continues to captivate audiences around the world.',
                    ]),
                ];
                break;

            case 'boardgames':
                $productData = [
                    'blog_title' => $this->faker->randomElement(['Discover New Adventures: Latest Board Game Releases', 'Top Picks for Board Game Enthusiasts: Must-Play Titles', 'Explore the World of Board Games: New Releases', 'Immerse Yourself in Board Game Magic: Highlights', 'Unlock the Joy of Board Gaming: Exciting Releases', 'Embark on Board Game Adventures: Reviews and Insights']),
                    'blog_description' => $this->faker->randomElement(['Discover the latest and greatest board games that will bring friends and families together.', 'Explore a world of board gaming with our curated list of top picks for enthusiasts.', 'Find out what\'s trending in board games with our comprehensive reviews and insights.', 'Get ready for a tabletop adventure with these exciting new board game releases.', 'Experience the joy of board gaming with these handpicked titles that promise fun for all.', 'Unlock the secrets of these new board games and embark on unforgettable tabletop adventures.']),
                    'content' => $this->faker->randomElement([
                        'Delve into the captivating world of board games, where strategy, luck, and camaraderie come together to create unforgettable gaming experiences. From classic favorites to innovative new releases, board games offer something for players of all ages and interests. Whether you\'re embarking on a quest for world domination in a strategic war game, solving mysteries in a cooperative adventure, or testing your wits in a fast-paced party game, each session promises laughter, excitement, and friendly competition. Gather around the table with friends and family, roll the dice, draw cards, and embark on journeys that challenge your intellect and foster lasting memories. Discover the joy of tabletop gaming and explore a diverse range of genres that cater to every gaming preference.',
                        'Find out about upcoming board game releases and exclusive previews.',
                        'Unleash your inner strategist with a collection of board games that blend tactical decision-making with immersive storytelling. From intricate Euro-style games that reward careful planning to thematic adventures that transport you to fantastical realms, board games offer a wealth of opportunities to test your skills and expand your horizons. Command armies, negotiate alliances, build civilizations, or uncover ancient mysteries as you navigate the twists and turns of each game\'s unique mechanics. Whether you\'re a seasoned player seeking new challenges or a newcomer eager to learn, our curated selection of board games ensures that there\'s always something new to discover. Immerse yourself in rich narratives, engage in epic battles, and forge unforgettable memories with every roll of the dice.',
                        'Immerse yourself in the world of board games with a collection of titles that celebrate creativity, strategy, and social interaction. Experience the thrill of outwitting opponents in intense strategic showdowns or collaborating with friends to overcome challenges and achieve victory. From fast-paced card games that test your reflexes to epic tabletop adventures that unfold over hours, each board game offers a unique blend of excitement and engagement. Dive into richly thematic worlds, explore complex game systems, and enjoy the tactile satisfaction of moving pieces across beautifully designed boards. Whether you prefer competitive duels or cooperative quests, our selection of board games invites you to explore new realms, hone your skills, and create unforgettable gaming experiences with every play session.',
                        'Step into the realm of board games where every roll of the dice and strategic move brings you closer to victory. Whether you\'re navigating treacherous waters in a nautical adventure, solving puzzles in a thrilling mystery game, or building civilizations through the ages, board games offer endless opportunities for exploration and discovery. Engage in lively debates, negotiate alliances, and outwit opponents with cunning tactics as you strive to achieve your objectives and emerge triumphant. With each game session, you\'ll sharpen your decision-making skills, cultivate teamwork, and immerse yourself in captivating narratives that unfold with every turn. From family-friendly classics to innovative new releases, board games provide entertainment and excitement for players of all ages and interests.',
                        'Embark on epic quests and engage in thrilling battles with a collection of board games that blend strategy, luck, and storytelling. Traverse vast landscapes, gather resources, and build powerful empires as you navigate the challenges and opportunities presented by each game\'s unique mechanics. Whether you\'re commanding armies in a historical war game, exploring uncharted territories in a fantasy adventure, or mastering the art of diplomacy in a political simulation, board games offer immersive experiences that captivate the imagination. Discover hidden treasures, forge alliances, and unleash your strategic prowess as you compete for dominance and prestige. With a diverse selection of genres and themes to choose from, board games invite you to explore new worlds, challenge your skills, and forge unforgettable memories with every play session.',
                        'Immerse yourself in the captivating world of board games, where every decision shapes the course of your journey and every victory is a testament to your strategic prowess. From thrilling space explorations to intense tactical battles, board games offer a myriad of experiences that cater to diverse interests and preferences. Command starships, conquer kingdoms, solve mysteries, and embark on heroic quests as you delve into richly thematic narratives and intricate game mechanics. Whether you\'re a seasoned strategist or a casual gamer, our curated selection of board games ensures that there\'s always something new to discover and enjoy. Gather your friends and family, roll the dice, draw cards, and embark on adventures that challenge your intellect and foster meaningful connections. With endless possibilities for fun and excitement, board games promise endless hours of entertainment and camaraderie for players of all skill levels.',
                    ]),
                ];
                break;

            default:
                $productData = [
                    'blog_title' => $this->faker->sentence,
                    'blog_description' => $this->faker->paragraph,
                    'content' => $this->faker->paragraphs(3, true),
                ];
                break;
        }

        return array_merge($productData, [
            'date' => $this->faker->dateTimeBetween('-1 year', 'now'),
        ]);
    }
}
